[font]
size = 10

normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[cursor.style]
shape =  "Beam"
blinking  = "Always"

[window.padding]
x = 5
y = 5

[window]

[general]
import = [
    "~/.config/alacritty/theme.toml"
]

